import React from "react"
import { DisclosureButton } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  DisclosureButton,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=43343%3A3360",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("state", {
        disabled: true,
      }),
      overline: figma.string("↳ overline"),
      subheading: figma.string("↳ subheader"),
      // No matching props could be found for these Figma properties:
      // "overline": figma.boolean('overline'),
      // "overline": figma.string('↳ overline'),
      // "header": figma.string('header'),
      // "subheader": figma.boolean('subheader'),
      // "subheader": figma.string('↳ subheader')
    },
    example: (props) => (
      <DisclosureButton
        disabled={props.disabled}
        heading={/* TODO */}
        overline={props.overline}
        subheading={props.subheading}
      />
    ),
  },
)
