import { IconButton } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  IconButton,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1106%3A90',
  {
    props: {
      icon: figma.instance('icon'),
      size: figma.enum('size', {
        normal: 'normal',
        small: 'small',
        large: 'large',
      }),
      toolTipInfo: figma.nestedProps('tooltip', {
        tip: figma.textContent('✏️ tooltip'),
      }),
    },
    example: (props) => <IconButton {...props} tip={props.toolTipInfo?.tip} />,
  }
);
