import { StrokeButton } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  StrokeButton,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1106%3A48',
  {
    props: {
      children: figma.string('✏️ label'),
      icon: figma.boolean('👁 leading icon', {
        true: figma.instance('↳ leading icon'),
        false: figma.boolean('👁 trailing icon', {
          true: figma.instance('↳ trailing icon'),
          false: undefined,
        }),
      }),
      variant: figma.enum('variant', {
        primary: 'primary',
        secondary: 'secondary',
        danger: 'danger',
      }),
      size: figma.enum('size', {
        normal: 'normal',
        small: 'small',
        large: 'large',
      }),
    },
    example: ({ children, ...props }) => (
      <StrokeButton {...props}>{children}</StrokeButton>
    ),
  }
);
