name: 'Validate Pull Request Context'
description: 'Ensure the workflow is running in a pull request context'

runs:
  using: 'composite'
  steps:
    - name: Ensure workflow is associated with a pull request
      shell: bash
      run: |
        if [[ -z "${{ github.event.pull_request.number }}" ]]; then
          echo "This workflow is not associated with a pull request; exiting"
          exit 1
        fi
