import figma from "@figma/code-connect"

import { Disclosure } from "./index"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

// NOT STARTED WITH, WOULD NEED TO UPDATE MORE PROPS IN FIGMA
figma.connect(
  Disclosure,
  "https://www.figma.com/design/2cQBxc5JTO0M38mcYARs7O/codeConnect?node-id=43343-19299&m=dev",
  {
    props: {
      variant: figma.enum("variant", {
        default: "default",
        subtle: "subtle",
        transparent: "transparent",
      }),
      hasBorder: figma.boolean("hasBorder"),
      spacing: figma.enum("spacing", {
        normal: "normal",
        condensed: "condensed",
        compact: "compact",
      }),
      isExpanded: figma.boolean("isExpanded"),
    },
    example: (props) => <Disclosure />,
  },
)
