import figma from '@figma/code-connect';
import React from 'react';

import { Disclosure } from './index';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Disclosure,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=43343%3A19299',
  {
    props: {
      variant: figma.enum('variant', {
        default: 'default',
        subtle: 'subtle',
        transparent: 'transparent',
      }),
      hasBorder: figma.boolean('hasBorder'),
      spacing: figma.enum('spacing', {
        normal: 'normal',
        condensed: 'condensed',
        compact: 'compact',
      }),
      isExpanded: figma.boolean('isExpanded'),
    },
    example: (props) => <Disclosure {...props} />,
  }
);
