import React from 'react';
import { Anchor } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Anchor,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=19220%3A21856',
  {
    props: {
      children: figma.string('✏️ label'),
      icon: figma.boolean('👁 leading icon', {
        true: figma.instance('↳ leading icon'),
        false: figma.boolean('👁 trailing icon', {
          true: figma.instance('↳ trailing icon'),
          false: undefined,
        }),
      }),
      iconPosition: figma.boolean('👁 leading icon', {
        true: 'left',
        false: figma.boolean('👁 trailing icon', {
          true: 'right',
          false: undefined,
        }),
      }),
      variant: figma.enum('variant', {
        Inline: 'inline',
        Interface: 'interface',
        Standard: 'standard',
        'Standard-secondary': 'standard-secondary',
      }),
    },
    example: ({ children, ...props }) => <Anchor {...props}>{children}</Anchor>,
  }
);
