import React from 'react';
import { Badge } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=8200%3A8349',
  {
    props: {
      children: figma.string('✏️ label'),
      icon: figma.instance('↳ icon'),
      variant: figma.enum('variant', {
        primary: 'primary',
        secondary: 'secondary',
        tertiary: 'tertiary',
        tertiaryFill: 'tertiaryFill',
        accent: 'accent',
      }),
      size: figma.enum('size', {
        base: 'base',
        sm: 'sm',
      }),
    },
    example: ({ children, ...props }: any) => (
      <Badge {...props}>{children}</Badge>
    ),
  }
);
