import { Drawer } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Drawer,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=6329%3A5480',
  {
    props: {
      alignContentContainer: figma.enum('openFrom', {
        left: 'left',
        right: 'right',
      }),
      expanded: figma.boolean('openFrom', {
        true: true,
        false: false,
      }),
      children: figma.textContent('text'),
    },
    example: ({ children, ...props }: any) => (
      <Drawer {...props}>{children}</Drawer>
    ),
  }
);
