import React from 'react';
import { FeatureShimmer } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FeatureShimmer,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=61568%3A44253',
  {
    props: {
      children: '{children}',
    },
    example: (props) => <FeatureShimmer>{props.children}</FeatureShimmer>,
  }
);
