import { FormGroup } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FormGroup,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=47031%3A18018',
  {
    props: {
      label: figma.string('✏️ label'),
      infoTip: figma.boolean('infoTip'),
      required: figma.boolean('required'),
      labelSize: figma.enum('size', {
        small: 'small',
        large: 'large',
      }),
      infoTipData: figma.nestedProps('infotip', {
        emphasis: figma.enum('emphasis', { low: 'low', high: 'high' }),
        disabled: figma.enum('state', {
          default: false,
          hover: false,
          active: false,
          focus: false,
          disabled: true,
        }),
      }),
      description: figma.boolean('description', {
        true: figma.textContent('description'),
      }),
      toolTipInfo: figma.nestedProps('.infotip-alignment', {
        alignment: figma.enum('alignment', {
          'top-left': 'top-left',
          'top-right': 'top-right',
          'bottom-left': 'bottom-left',
          'bottom-right': 'bottom-right',
        }),
        info: figma.textContent('✏️ tip'),
      }),
    },
    example: (props) => (
      <FormGroup
        {...props}
        disabled={props.infoTipData?.disabled}
        infotip={{
          emphasis: props.infoTipData?.emphasis,
          info: props.toolTipInfo?.info,
          alignment: props.toolTipInfo?.alignment,
        }}
      />
    ),
  }
);
