import { ProgressBar } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ProgressBar,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=18640%3A20613',
  {
    props: {
      variant: figma.enum('variant', {
        default: 'default',
        yellow: 'yellow',
        blue: 'blue',
      }),
      size: figma.enum('size', {
        Small: 'small',
        Medium: 'medium',
        Large: 'large',
        XL: 'xl',
      }),
      percent: figma.enum('percent', {
        '0%': 0,
        '25%': 25,
        '50%': 50,
        '75%': 75,
        '100%': 100,
      }),
      flat: figma.enum('flat', {
        'flat-top': 'flat-top',
        'flat-bottom': 'flat-bottom',
      }),
      pattern: figma.boolean('pattern', {
        true: figma.children('.pattern-background'),
        false: undefined,
      }),
    },
    example: (props) => <ProgressBar {...props} />,
  }
);
