import { RadialProgress } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  RadialProgress,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=19788%3A33606',
  {
    props: {
      strokeLinecap: figma.enum('strokeLinecap', {
        round: 'round',
        butt: 'butt',
        square: 'square',
      }),
      baseColor: figma.enum('color', {
        text: 'text',
        'yellow-500': 'yellow-500',
      }),
      value: figma.enum('value', {
        '0%': 0,
        '10%': 10,
        '20%': 20,
        '30%': 30,
        '40%': 40,
        '50%': 50,
        '60%': 60,
        '70%': 70,
        '80%': 80,
        '90%': 90,
        '100%': 100,
      }),
      children: figma.boolean('children', {
        true: figma.enum('value', {
          '0%': 0,
          '10%': 10,
          '20%': 20,
          '30%': 30,
          '40%': 40,
          '50%': 50,
          '60%': 60,
          '70%': 70,
          '80%': 80,
          '90%': 90,
          '100%': 100,
        }),
        false: undefined,
      }),
    },
    example: ({ children, ...props }) => (
      <RadialProgress {...props}>{children}</RadialProgress>
    ),
  }
);
