import React from 'react';
import { SkipToContent } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  SkipToContent,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=18679%3A19731',
  {
    props: {
      contentId: 'id-of-where-to-skip-to',
    },
    example: (props) => <SkipToContent {...props} />,
  }
);
