import React from 'react';
import { MenuItem } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  MenuItem,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1971-2476',
  {
    props: {
      active: figma.boolean('active'),
      icon: figma.boolean('leading-icon', {
        true: figma.instance('↳ icon'),
        false: undefined,
      }),
      label: figma.boolean('label', {
        true: figma.string('↳ label'),
        false: undefined,
      }),
    },
    example: ({ label, ...props }) => <MenuItem {...props}>{label}</MenuItem>,
  }
);
