import figma from '@figma/code-connect';
import React from 'react';

import { MenuItem } from './MenuItem';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  MenuItem,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1971-2489',
  {
    props: {
      active: figma.boolean('active'),
      hover: figma.boolean('hover'),
      icon: figma.instance<React.FunctionComponent>('InstanceSwapPropName'),
      label: figma.string('label'),
    },
    example: ({ label, ...props }) => <MenuItem {...props}>{label}</MenuItem>,
  }
);
