import React from 'react';
import { Menu } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Menu,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1971%3A2562',
  {
    props: {
      variant: figma.enum('Variant', {
        popover: 'popover',
        fixed: 'fixed',
      }),
      spacing: figma.enum('Spacing', {
        normal: 'normal',
        condensed: 'condensed',
      }),
      children: figma.children('*'),
    },
    example: ({ children, ...props }) => <Menu {...props}>{children}</Menu>,
  }
);
