export const resourcesList = [
  {
    id: 'docs',
    href: '/resources/docs',
    headerTrackingTarget: 'topnav_resources_docs',
    footerTrackingTarget: 'docs',
    text: 'Docs',
    type: 'link',
  },
  {
    id: 'cheatsheets',
    href: '/resources/cheatsheets/all',
    headerTrackingTarget: 'topnav_resources_cheatsheets',
    footerTrackingTarget: 'cheatsheets_home',
    text: 'Cheatsheets',
    type: 'link',
  },
  {
    id: 'projects',
    href: '/projects',
    headerTrackingTarget: 'topnav_resources_projects',
    footerTrackingTarget: 'projects',
    text: 'Projects',
    type: 'link',
  },
  {
    id: 'articles',
    href: '/articles',
    headerTrackingTarget: 'topnav_resources_articles',
    footerTrackingTarget: 'articles',
    text: 'Articles',
    type: 'link',
  },
  {
    id: 'blog',
    href: 'https://codecademy.com/resources/blog',
    newTab: true,
    headerTrackingTarget: 'topnav_resources_blog',
    footerTrackingTarget: 'blog',
    text: 'Blog',
    type: 'link',
  },
];
