import React from "react"
import { Toaster } from "./index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Toaster,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=19674%3A29150",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "active": figma.boolean('Active'),
      // "toast": figma.boolean('Toast '),
      // "toast": figma.boolean('Toast '),
      // "toast": figma.boolean('Toast '),
      // "toast": figma.boolean('Toast ')
    },
    example: (props) => <Toaster toasts={/* TODO */} onClose={/* TODO */} />,
  },
)
