name: 'Setup Node & yarn'
description: 'Setup a NodeJS environment, install deps, & builds packages'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version-file: .nvmrc
    - name: Enable Corepack and prepare Yarn 4
      run: corepack enable
      shell: bash
    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
