name: 'Setup Node & yarn'
description: 'Setup a NodeJS environment, install deps, & builds packages'

inputs:
  immutable:
    description: 'Run yarn install with --immutable (fail if lockfile would change)'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version-file: .nvmrc
    - name: Enable Corepack and prepare Yarn 4
      run: corepack enable
      shell: bash
    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.immutable }}" = "true" ]; then
          yarn install --immutable
        else
          yarn install
        fi
