name: 'Setup Node & yarn'
description: 'Setup a NodeJS environment, install deps, & builds packages'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
      with:
        node-version-file: .nvmrc
    - name: Enable Corepack (Yarn 4)
      run: corepack enable
      shell: bash
    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
