name: 'Restore Yarn Cache'
description: 'Setup a NodeJS environment and restore cache if any, given a node version'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
    - uses: actions/cache@v4
      with:
        path: |
          **/node_modules
        key: v1-yarn-${{ runner.os }}-${{ hashFiles('.nvmrc') }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install Dependencies If Not Cached
      run: \[ -d node_modules \] || yarn install --immutable
      shell: bash
