version: "2"
checks:
  similar-code:
    enabled: false
  identical-code:
    enabled: false
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
  scss-lint:
    enabled: true
exclude_patterns:
  - "config/"
  - "db/"
  - "dist/"
  - "features/"
  - "**/node_modules/"
  - "script/"
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - "**/vendor/"
  - "**/*-test.js*"
  - "**/*-story.js*"
