codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 4 # Must be the # of parallel test builds in CircleCI
    wait_for_ci: yes

comment:
  after_n_builds: 4 # Must be the # of parallel test builds in CircleCI
  layout: "diff, files"
  require_changes: true

coverage:
  status:
    project:
      gamut:  # declare a new status context "tests"
        target: 100%  # we always want 100% coverage here
        paths: "packages/gamut/"  # only include coverage in "tests/" folder

ignore:
  - "**/*.js"
  - "**/*.md"
  - "**/*.mdx"
