// This file is generated by eslint-config-codecademy
// to edit these rules, modify the eslint-config-codecademy package
module.exports = {
  singleQuote: true,
  trailingComma: 'es5',
  tabWidth: 2,
  useTabs: false,
  overrides: [
    {
      files: '*.{scss,css}',
      options: {
        parser: 'css',
        singleQuote: false,
        semi: true,
      },
    },
  ],
};
