// The one static stylesheet a consumer imports (generated by `npm run cssgen`).
// Replaces Emotion's runtime cache + <Global> injection entirely.
import './gamut-static.css';

import { createRoot } from 'react-dom/client';

import { App } from './App';

createRoot(document.getElementById('root')!).render(<App />);
