// Real Gamut Core web fonts (Apercu/Suisse) + the one static stylesheet a
// consumer imports (generated by cssgen). Replaces Emotion's cache + <Global>.
import './fonts.css';
import './gamut-static.css';

import { createRoot } from 'react-dom/client';

import { App } from './App';

createRoot(document.getElementById('root')!).render(<App />);
