import React from 'react';
import { DataTable } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DataTable,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=9922-48146',
  {
    props: {
      size: figma.enum('Size', {
        Normal: 'normal',
        Condensed: 'condensed',
      }),
      columns: [
        {
          key: 'name',
          header: 'Name',
          size: 'xl',
          sortable: true,
        },
        {
          key: 'row1',
          header: 'Row #',
          size: 'sm',
          sortable: true,
        },
        {
          key: 'row2',
          header: 'Row #',
          size: 'sm',
          sortable: true,
        },
      ],
      rows: [
        { name: 'Text Content', row1: '1', row2: '1' },
        { name: 'Text Content', row1: '2', row2: '2' },
        { name: 'Text Content', row1: '3', row2: '3' },
        { name: 'Text Content', row1: '4', row2: '4' },
        { name: 'Text Content', row1: '5', row2: '5' },
        { name: 'Text Content', row1: '6', row2: '6' },
        { name: 'Text Content', row1: '7', row2: '7' },
        { name: 'Text Content', row1: '8', row2: '8' },
        { name: 'Text Content', row1: '9', row2: '9' },
        { name: 'Text Content', row1: '10', row2: '10' },
      ],
    },
    example: (props) => <DataTable {...props} />,
  }
);
