import { Toaster } from '@codecademy/gamut';
import { Bee } from '@codecademy/gamut-illustrations';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Toaster,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=19674%3A29150',
  {
    props: {
      toasts: figma.boolean('Toast #1', {
        true: figma.boolean('Toast #2', {
          true: figma.boolean('Toast #3', {
            true: figma.boolean('Toast #4', {
              true: [
                {
                  id: 'toast1',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                  icon: <Bee />,
                },
                {
                  id: 'toast2',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  icon: <Bee />,
                },
                {
                  id: 'toast3',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                },
                {
                  id: 'toast4',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                },
              ],
              false: [
                {
                  id: 'toast1',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                  icon: <Bee />,
                },
                {
                  id: 'toast2',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  icon: <Bee />,
                },
                {
                  id: 'toast3',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                },
              ],
            }),
            false: figma.boolean('Toast #4', {
              true: [
                {
                  id: 'toast1',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                  icon: <Bee />,
                },
                {
                  id: 'toast2',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  icon: <Bee />,
                },
                {
                  id: 'toast4',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                },
              ],
              false: [
                {
                  id: 'toast1',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                  icon: <Bee />,
                },
                {
                  id: 'toast2',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  icon: <Bee />,
                },
              ],
            }),
          }),
          false: figma.boolean('Toast #3', {
            true: figma.boolean('Toast #4', {
              true: [
                {
                  id: 'toast1',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                  icon: <Bee />,
                },
                {
                  id: 'toast3',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                },
                {
                  id: 'toast4',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                },
              ],
              false: [
                {
                  id: 'toast1',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                  icon: <Bee />,
                },
                {
                  id: 'toast3',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                },
              ],
            }),
            false: figma.boolean('Toast #4', {
              true: [
                {
                  id: 'toast1',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                  icon: <Bee />,
                },
                {
                  id: 'toast4',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                },
              ],
              false: [
                {
                  id: 'toast1',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                  icon: <Bee />,
                },
              ],
            }),
          }),
        }),
        false: figma.boolean('Toast #2', {
          true: figma.boolean('Toast #3', {
            true: figma.boolean('Toast #4', {
              true: [
                {
                  id: 'toast2',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  icon: <Bee />,
                },
                {
                  id: 'toast3',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                },
                {
                  id: 'toast4',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                },
              ],
              false: [
                {
                  id: 'toast2',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  icon: <Bee />,
                },
                {
                  id: 'toast3',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                },
              ],
            }),
            false: figma.boolean('Toast #4', {
              true: [
                {
                  id: 'toast2',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  icon: <Bee />,
                },
                {
                  id: 'toast4',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                },
              ],
              false: [
                {
                  id: 'toast2',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  icon: <Bee />,
                },
              ],
            }),
          }),
          false: figma.boolean('Toast #3', {
            true: figma.boolean('Toast #4', {
              true: [
                {
                  id: 'toast3',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                },
                {
                  id: 'toast4',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                },
              ],
              false: [
                {
                  id: 'toast3',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                  title: 'Title with Optional Icon',
                },
              ],
            }),
            false: figma.boolean('Toast #4', {
              true: [
                {
                  id: 'toast4',
                  children:
                    'Keep Body Text within Toasts to a maximum of 3 lines of text.',
                },
              ],
              false: [],
            }),
          }),
        }),
      }),
    },
    example: (props) => <Toaster toasts={props.toasts} />,
  }
);
