import { Toast } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Toast,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1115%3A195',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      title: figma.enum('Title', {
        true: figma.string('title'),
        false: undefined,
      }),
      // No matching props could be found for these Figma properties:
      // "cta": figma.boolean('cta'),
      // "title": figma.string('title'),
      // "description": figma.string('description'),
      iconProps: figma.nestedProps('📐 Content', {
        icon: figma.boolean('Image', {
          true: 'test',
          false: 'false',
        }),
      }),
      icon: figma.boolean('Image', {
        true: figma.children('*'),
        false: undefined,
      }),
      body: figma.string('description'),
    },
    example: ({ body, title, iconProps, ...props }) => (
      <Toast icon={iconProps.icon} {...props}>
        {title} {body}
      </Toast>
    ),
  }
);
