import React from 'react';
import { Toast } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Toast,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=117004-53652',
  {
    props: {
      title: figma.boolean('title', {
        true: figma.string('↳ title'),
        false: undefined,
      }),
      iconProps: figma.nestedProps('content', {
        icon: figma.children('*')
      }),
      icon: figma.boolean('icon', {
        true: <SomeReactNode />,
        false: undefined,
      }),
      children: figma.boolean('description', {
        true: figma.string('↳ description'),
        false: undefined,
      }),
    },
    example: ({ children, iconProps, ...props }) => (
      <Toast {...props}>
        {children}
      </Toast>
    ),
  }
);
