import { Toast } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Toast,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1115%3A195',
  {
    props: {
      title: figma.boolean('Title', {
        true: figma.textContent('Title'),
        false: undefined,
      }),
      iconProps: figma.nestedProps('📐 Content', {
        icon: figma.boolean('Image', {
          true: 'test',
          false: 'false',
        }),
      }),
      icon: figma.boolean('Image', {
        true: figma.children('*'),
        false: undefined,
      }),
      children: figma.string('description'),
    },
    example: ({ children, iconProps, ...props }) => (
      <Toast icon={iconProps.icon} {...props}>
        {children}
      </Toast>
    ),
  }
);
