import React from 'react';
import { Modal } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Modal,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=130899-13648',
  {
    props: {
      title: figma.string('title'),
      children: figma.textContent('✏️ description'),
      image: figma.boolean('Image', {
        true: figma.children('.image'),
        false: undefined,
      }),
      size: figma.enum('size', {
        small: 'small',
        medium: 'medium',
        large: 'large',
        fluid: 'fluid',
      }),
      views: figma.boolean('views', {
        true: [
          {
            title: 'First view title',
            children: 'First view description',
            primaryCta: {
              actionType: 'confirm',
              children: 'Next'
            },
            secondaryCta: {
              actionType: 'cancel',
              children: 'Cancel'
            },
          },
        ],
        false: undefined,
      }),
      isOpen: true,
    },
    example: ({ children, ...props }) => (
      <Modal
        {...props}
        onRequestClose={() => { }}
      >
        {children}
      </Modal>
    ),
  }
);
