import { Modal } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Modal,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=19560%3A29540',
  {
    props: {
      modalProps: figma.nestedProps('Dialog', {
        image: figma.boolean('Image', {
          true: figma.children('.image'),
          false: undefined,
        }),
        children: figma.textContent('✏️ description'),
        size: figma.enum('size', {
          small: 'small',
          medium: 'medium',
          large: 'large',
          fluid: 'fluid',
        }),
        variant: figma.enum('variant', {
          primary: 'primary',
          danger: 'danger',
        }),
        title: figma.textContent('✏️ title'),
      }),
    },
    example: ({ modalProps }: any) => (
      <Modal
        image={modalProps.image}
        size={modalProps.size}
        title={modalProps.title}
        variant={modalProps.variant}
      >
        {modalProps.children}
      </Modal>
    ),
  }
);
