/* GENERATED by src/precompute/generate.ts — do not edit.
 *
 * Produced by EXECUTING the unchanged variance authoring in ./authoring.ts and
 * enumerating its variant/state space. The authoring file keeps
 * `templateVariants`, computed enum keys, `transitionConcat()` and ternaries —
 * none of which a parse-based codemod could handle. */
import { defineRecipe } from '@pandacss/dev';

type RecipeConfig = Parameters<typeof defineRecipe>[0];

export const generatedFillButton = defineRecipe({
  className: 'gmt-gen-fill-button',
  base: {
    transition:
      '[border-color 150ms ease-in,color 150ms ease-in,background-color 150ms ease-in,box-shadow 150ms ease-in]',
    border: '[2px solid var(--color-border-primary)]',
    borderColor: '[transparent]',
    whiteSpace: '[nowrap]',
    justifyContent: '[center]',
    alignItems: '[center]',
    display: '[inline-flex]',
    position: '[relative]',
    borderRadius: '[4px]',
    "[disabled], &:disabled, &[aria-disabled='true']": {
      cursor: '[not-allowed]',
      userSelect: '[none]',
    },
    '&:before': {
      content: '[""]',
      border: '[2px solid var(--color-border-primary)]',
      position: '[absolute]',
      insetBlockStart: '[-5px]',
      insetInlineEnd: '[-5px]',
      insetBlockEnd: '[-5px]',
      insetInlineStart: '[-5px]',
      zIndex: '[0]',
      opacity: '[0]',
      borderRadius: '[8px]',
    },
    '&:focus-visible:before': {
      opacity: '[1]',
    },
  },
  variants: {
    variant: {
      primary: {
        color: '[var(--color-background)]',
        backgroundColor: '[var(--color-primary)]',
        '&:before': {
          borderColor: '[var(--color-primary)]',
        },
        '&:hover': {
          transition:
            '[background-color 150ms ease-in,box-shadow 150ms ease-in]',
          color: '[var(--color-background)]',
          backgroundColor: '[var(--color-primary-hover)]',
        },
        '&:active': {
          borderColor: '[var(--color-border-primary)]',
          color: '[var(--color-background)]',
          backgroundColor: '[var(--color-primary)]',
        },
        "[disabled], &:disabled, &[aria-disabled='true']": {
          color: '[var(--color-text-disabled)]',
          backgroundColor: '[var(--color-background-disabled)]',
        },
      },
      secondary: {
        color: '[var(--color-background)]',
        backgroundColor: '[var(--color-secondary)]',
        '&:before': {
          borderColor: '[var(--color-secondary)]',
        },
        '&:hover': {
          transition:
            '[background-color 150ms ease-in,box-shadow 150ms ease-in]',
          color: '[var(--color-background)]',
          backgroundColor: '[var(--color-secondary-hover)]',
        },
        '&:active': {
          borderColor: '[var(--color-border-primary)]',
          color: '[var(--color-background)]',
          backgroundColor: '[var(--color-secondary)]',
        },
        "[disabled], &:disabled, &[aria-disabled='true']": {
          color: '[var(--color-text-disabled)]',
          backgroundColor: '[var(--color-background-disabled)]',
        },
      },
      danger: {
        color: '[var(--color-background)]',
        backgroundColor: '[var(--color-danger)]',
        '&:before': {
          borderColor: '[var(--color-danger)]',
        },
        '&:hover': {
          transition:
            '[background-color 150ms ease-in,box-shadow 150ms ease-in]',
          color: '[var(--color-background)]',
          backgroundColor: '[var(--color-danger-hover)]',
        },
        '&:active': {
          borderColor: '[var(--color-border-primary)]',
          color: '[var(--color-background)]',
          backgroundColor: '[var(--color-danger)]',
        },
        "[disabled], &:disabled, &[aria-disabled='true']": {
          color: '[var(--color-text-disabled)]',
          backgroundColor: '[var(--color-background-disabled)]',
        },
      },
      interface: {
        color: '[var(--color-background)]',
        backgroundColor: '[var(--color-interface)]',
        '&:before': {
          borderColor: '[var(--color-interface)]',
        },
        '&:hover': {
          transition:
            '[background-color 150ms ease-in,box-shadow 150ms ease-in]',
          color: '[var(--color-background)]',
          backgroundColor: '[var(--color-interface-hover)]',
        },
        '&:active': {
          borderColor: '[var(--color-border-primary)]',
          color: '[var(--color-background)]',
          backgroundColor: '[var(--color-interface)]',
        },
        "[disabled], &:disabled, &[aria-disabled='true']": {
          color: '[var(--color-text-disabled)]',
          backgroundColor: '[var(--color-background-disabled)]',
        },
      },
    },
    size: {
      small: {
        paddingInlineStart: '[0.5rem]',
        paddingInlineEnd: '[0.5rem]',
        paddingBlockStart: '[0.25rem]',
        paddingBlockEnd: '[0.25rem]',
        fontSize: '[0.875rem]',
        minBlockSize: '[32px]',
      },
      normal: {
        paddingInlineStart: '[1rem]',
        paddingInlineEnd: '[1rem]',
        paddingBlockStart: '[0.25rem]',
        paddingBlockEnd: '[0.25rem]',
        fontSize: '[1rem]',
        minBlockSize: '[40px]',
      },
      large: {
        paddingInlineStart: '[1rem]',
        paddingInlineEnd: '[1rem]',
        paddingBlockStart: '[0.25rem]',
        paddingBlockEnd: '[0.25rem]',
        fontSize: '[1.125rem]',
        minBlockSize: '[56px]',
      },
    },
    fullWidth: {
      true: {
        inlineSize: '[100%]',
      },
    },
  },
  defaultVariants: {
    variant: 'primary',
    size: 'normal',
  },
} as RecipeConfig);

export const generatedTextButton = defineRecipe({
  className: 'gmt-gen-text-button',
  base: {
    transition:
      '[border-color 150ms ease-in,color 150ms ease-in,background-color 150ms ease-in,box-shadow 150ms ease-in]',
    border: '[2px solid var(--color-border-primary)]',
    borderColor: '[transparent]',
    whiteSpace: '[nowrap]',
    justifyContent: '[center]',
    alignItems: '[center]',
    display: '[inline-flex]',
    position: '[relative]',
    borderRadius: '[4px]',
    "[disabled], &:disabled, &[aria-disabled='true']": {
      cursor: '[not-allowed]',
      userSelect: '[none]',
    },
    '&:before': {
      content: '[""]',
      border: '[2px solid var(--color-border-primary)]',
      position: '[absolute]',
      insetBlockStart: '[-5px]',
      insetInlineEnd: '[-5px]',
      insetBlockEnd: '[-5px]',
      insetInlineStart: '[-5px]',
      zIndex: '[0]',
      opacity: '[0]',
      borderRadius: '[8px]',
    },
    '&:focus-visible:before': {
      opacity: '[1]',
    },
  },
  variants: {
    variant: {
      primary: {
        borderColor: '[transparent]',
        color: '[var(--color-primary)]',
        '&:hover': {
          transition:
            '[background-color 150ms ease-in,box-shadow 150ms ease-in]',
          color: '[var(--color-primary)]',
          backgroundColor: '[var(--color-background-hover)]',
        },
        '&:focus-visible': {
          color: '[var(--color-primary)]',
        },
        "[disabled], &:disabled, &[aria-disabled='true']": {
          color: '[var(--color-text-disabled)]',
          backgroundColor: '[transparent]',
        },
      },
      secondary: {
        borderColor: '[transparent]',
        color: '[var(--color-secondary)]',
        '&:hover': {
          transition:
            '[background-color 150ms ease-in,box-shadow 150ms ease-in]',
          color: '[var(--color-secondary)]',
          backgroundColor: '[var(--color-background-hover)]',
        },
        '&:focus-visible': {
          color: '[var(--color-secondary)]',
        },
        "[disabled], &:disabled, &[aria-disabled='true']": {
          color: '[var(--color-text-disabled)]',
          backgroundColor: '[transparent]',
        },
      },
      danger: {
        borderColor: '[transparent]',
        color: '[var(--color-danger)]',
        '&:hover': {
          transition:
            '[background-color 150ms ease-in,box-shadow 150ms ease-in]',
          color: '[var(--color-danger)]',
          backgroundColor: '[var(--color-background-hover)]',
        },
        '&:focus-visible': {
          color: '[var(--color-danger)]',
        },
        "[disabled], &:disabled, &[aria-disabled='true']": {
          color: '[var(--color-text-disabled)]',
          backgroundColor: '[transparent]',
        },
      },
      interface: {
        borderColor: '[transparent]',
        color: '[var(--color-text)]',
        '&:hover': {
          transition:
            '[background-color 150ms ease-in,box-shadow 150ms ease-in]',
          color: '[var(--color-interface)]',
          backgroundColor: '[var(--color-background-hover)]',
        },
        '&:focus-visible': {
          color: '[var(--color-interface)]',
        },
        "[disabled], &:disabled, &[aria-disabled='true']": {
          color: '[var(--color-text-disabled)]',
          backgroundColor: '[transparent]',
        },
      },
    },
    size: {
      small: {
        paddingInlineStart: '[0.5rem]',
        paddingInlineEnd: '[0.5rem]',
        paddingBlockStart: '[0.25rem]',
        paddingBlockEnd: '[0.25rem]',
        fontSize: '[0.875rem]',
        minBlockSize: '[32px]',
      },
      normal: {
        paddingInlineStart: '[1rem]',
        paddingInlineEnd: '[1rem]',
        paddingBlockStart: '[0.25rem]',
        paddingBlockEnd: '[0.25rem]',
        fontSize: '[1rem]',
        minBlockSize: '[40px]',
      },
      large: {
        paddingInlineStart: '[1rem]',
        paddingInlineEnd: '[1rem]',
        paddingBlockStart: '[0.25rem]',
        paddingBlockEnd: '[0.25rem]',
        fontSize: '[1.125rem]',
        minBlockSize: '[56px]',
      },
    },
    fullWidth: {
      true: {
        inlineSize: '[100%]',
      },
    },
  },
  defaultVariants: {
    variant: 'primary',
    size: 'normal',
  },
} as RecipeConfig);

export const generatedOverlap = defineRecipe({
  className: 'gmt-gen-overlap',
  base: {},
  variants: {
    warning: {
      true: {
        backgroundColor: '[var(--color-yellow)]',
      },
    },
    error: {
      true: {
        backgroundColor: '[var(--color-red)]',
      },
    },
  },
  defaultVariants: {},
} as RecipeConfig);
