import React from 'react';
import cx from 'classnames';

import generateClassnames from '../utils/generateClassnames';
import {
  ResponsiveProperty,
  OptionalResponsiveProperty,
} from '../typings/responsive-properties';

import s from './styles/ListColumn.module.scss';

/**
 * These types map to class names generated by our CSS Modules,
 * please refer to values specified in `./styles/variables.scss`
 * as a reference to their function.
 */
export type FlexColumnSizes =
  | 'xs'
  | 'sm'
  | 'md'
  | 'lg'
  | 'xl'
  | 'xxl'
  | 'content'
  | 'fill'
  | 'max';

export type Alignments = 'center' | 'left' | 'right';
export type FlushDirections = 'left' | 'right';
export type PaddingSizes = 'none' | 'sm' | 'md';

export type ListColumnProps = {
  // Specify a flex-basis for for column or a flex grow.
  size?: ResponsiveProperty<FlexColumnSizes>;
  // Align column content
  align?: OptionalResponsiveProperty<Alignments>;
  // Remove padding on the left or right side
  flush?: OptionalResponsiveProperty<FlushDirections>;
  // Set column padding
  padding?: OptionalResponsiveProperty<PaddingSizes>;
};

export const ListColumn: React.FC<ListColumnProps> = React.memo(
  ({ padding = 'sm', flush, size = 'content', align, children }) => {
    return (
      <div
        className={cx(
          s.listColumn,
          generateClassnames({ padding, flush, size, align }, s)
        )}
      >
        {children}
      </div>
    );
  }
);

export default ListColumn;
