import React from 'react';
import { Tag } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Tag,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=50740-63246',
  {
    props: {
      children: figma.string('label'),
      icon: figma.boolean('leading icon', {
        true: figma.instance('↳ leading icon'),
        false: undefined,
      }),
      variant: 'selection',
      size: figma.enum('size', {
        default: 'default',
        large: 'large',
      }),
    },
    example: ({ children, ...props }) => <Tag {...props}>{children}</Tag>,
  }
);
