import React from 'react';
import { DataTable } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */
figma.connect(
  DataTable,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=134718-26625',
  {
    props: {
      spacing: figma.enum('spacing', {
        condensed: 'condensed',
        normal: 'normal',
        compact: 'compact',
      }),
      scrollable: figma.boolean('scrollable'),
      shadow: figma.boolean('shadow'),
      rows: figma.boolean('showEmptyState', {
        true: [],
        false: [
          { header1: 'Cell', header2: 'Cell', header3: 'Cell', header4: 'Cell' },
          { header1: 'Cell', header2: 'Cell', header3: 'Cell', header4: 'Cell' },
          { header1: 'Cell', header2: 'Cell', header3: 'Cell', header4: 'Cell' },
          { header1: 'Cell', header2: 'Cell', header3: 'Cell', header4: 'Cell' },
          { header1: 'Cell', header2: 'Cell', header3: 'Cell', header4: 'Cell' },
          { header1: 'Cell', header2: 'Cell', header3: 'Cell', header4: 'Cell' },
          { header1: 'Cell', header2: 'Cell', header3: 'Cell', header4: 'Cell' },
          { header1: 'Cell', header2: 'Cell', header3: 'Cell', header4: 'Cell' },
          { header1: 'Cell', header2: 'Cell', header3: 'Cell', header4: 'Cell' },
          { header1: 'Cell', header2: 'Cell', header3: 'Cell', header4: 'Cell' },
        ],
      }),

    },
    example: ({ spacing, scrollable, shadow, rows }) => {
      const columns = [
        { key: 'header1', header: 'Header', type: 'header', size: 'xl', sortable: true },
        { key: 'header2', header: 'Header', size: 'md', sortable: true },
        { key: 'header3', header: 'Header', size: 'md', sortable: true },
        { key: 'header4', header: 'Header', size: 'md', sortable: true },
        { key: 'header5', header: 'Header', type: 'control', size: 'md' },
      ];

      return (
        <DataTable
          id="example"
          idKey="header1"
          spacing={spacing}
          scrollable={scrollable}
          shadow={shadow}
          columns={columns}
          rows={rows}
        />
      )
    },
  }
);
