import React from 'react';
import { GridForm } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  GridForm,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1689%3A4007',
  {
    props: {
      fields: figma.enum('Template', {
        Starter: [
          {
            label: 'Form element label',
            name: 'form-element-label',
            size: 12,
            type: 'text',
            validation: { required: true },
          },
          {
            label: 'Form element label',
            name: 'form-element-label-2',
            size: 6,
            type: 'text',
            validation: { required: true },
          },
          {
            label: 'Form element label',
            name: 'form-element-label-3',
            size: 6,
            type: 'text',
            validation: { required: true },
          },
          {
            description: 'Label',
            name: 'form-checkbox',
            size: 6,
            type: 'checkbox',
          },
          {
            label: 'Radio Group',
            name: 'form-radio-group',
            size: 6,
            type: 'radio-group',
            options: [
              {
                label: 'Label',
                value: 'label-1',
              },
              {
                label: 'Label',
                value: 'label-2',
              },
            ],
          },
        ],
        Sections: [
          {
            title: 'Section Header',
            layout: 'left',
            variant: 'title-md',
            fields: [
              {
                label: 'Form element label',
                name: 'form-element-label',
                size: 9,
                type: 'text',
                validation: { required: true },
              },
              {
                label: 'Form element label',
                name: 'form-element-label-2',
                size: 9,
                type: 'file',
                validation: { required: true },
              },
            ],
          },
          {
            title: 'Section Header',
            layout: 'left',
            variant: 'title-md',
            fields: [
              {
                label: 'Form element label',
                name: 'form-element-label',
                size: 9,
                type: 'textarea',
                validation: { required: true },
                rows: 5,
              },
            ],
          },
        ],
        'Inline Submit': [
          {
            label: 'Form element label',
            name: 'form-element-label',
            size: 8,
            type: 'text',
          },
        ],
      }),
      submit: figma.enum('Template', {
        Starter: {
          contents: 'Submit form',
          position: 'left',
          size: 12,
        },
        Sections: {
          contents: 'Submit form',
          position: 'right',
          size: 12,
          type: 'cta',
        },
        'Inline Submit': {
          contents: 'Submit Form',
          size: 4,
          position: 'right',
        },
      }),
      cancel: figma.enum('Template', {
        Sections: {
          children: 'Cancel',
          onClick: () => {},
        },
      }),
    },
    example: (props) => <GridForm {...props} />,
  }
);
