import React from "react"
import { MenuItem } from "./MenuItem"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  MenuItem,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=57295%3A20592",
  {
    props: {
      leadingIcon: figma.boolean("leadingIcon"),
      trailingIcon: figma.boolean("trailingIcon"),
      label: figma.string("label"),
      state: figma.enum("state", {
        default: "default",
        hover: "hover",
        selected: "selected",
      }),
    },
    example: (props) => <MenuItem />,
  },
)
