import { Alert } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Alert,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1118-23',
  {
    props: {
      type: figma.enum('Type', {
        General: 'info',
        Success: 'success',
        Error: 'error',
        Subtle: 'subtle',
        Warning: 'warning',
        Feature: 'feature',
      }),
      onClose: figma.boolean('Dismissable', {
        true: () => {
          // Dismiss logic goes here
        },
        false: undefined,
      }),
      cta: figma.boolean('CTA', {
        true: 'Learn more',
        false: undefined,
      }),
      alertBase: figma.nestedProps('.alert-base', {
        children: figma.textContent('text'),
      }),
    },
    example: ({ alertBase, ...props }: any) => (
      <Alert {...props} placement="floating">
        {alertBase.children}
      </Alert>
    ),
  }
);
