import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Sidebar order follows the docs folder structure; each top-level section's
// `_category_.json` position matches ADR 0001's navigation order.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
