import React from 'react';
import { Alert } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Alert,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=27627-31065',
  {
    props: {
      type: figma.enum('type', {
        general: 'info',
        success: 'success',
        error: 'error',
        subtle: 'subtle',
        warning: 'warning',
        feature: 'feature',
      }),
      onClose: figma.boolean('dismissible', {
        true: () => {
          // Dismiss logic goes here
        },
        false: undefined,
      }),
      cta: figma.boolean('CTA', {
        true: 'Learn more',
        false: undefined,
      }),
      children: figma.textContent('text'),
      placement: figma.enum('placement', {
        inline: 'inline',
        floating: 'floating',
      }),
    },
    example: ({ children, ...props }) => (
      <Alert {...props} >
        {children}
      </Alert>
    ),
  }
);
