import { Breadcrumbs } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Breadcrumbs,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=54229%3A24977',
  {
    props: {
      currenttitle: figma.string('current-title'),
      crumb1: figma.boolean('crumb-1', {
        true: {
          href: '/crumb-1',
          title: 'Crumb 1',
        },
      }),
      crumb2: figma.boolean('crumb-2', {
        true: {
          href: '/crumb-2',
          title: 'Crumb 2',
        },
      }),

      crumb3: figma.boolean('crumb-3', {
        true: {
          href: '/crumb-3',
          title: 'Crumb 3',
        },
      }),
    },
    example: (props) => {
      <Breadcrumbs
        crumbs={[
          props.crumb1,
          props.crumb2,
          props.crumb3,
          { href: '/current-page', title: props.currenttitle },
        ]}
      />;
    },
  }
);
