import React from 'react';
import { Breadcrumbs } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Breadcrumbs,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=54229%3A24977',
  {
    props: {
      crumbs: figma.boolean('crumb-1', {
        true: figma.boolean('crumb-2', {
          true: figma.boolean('crumb-3', {
            true: [
              {
                href: '/homepage',
                title: 'Home',
              },
              {
                href: '/crumb-1',
                title: 'There',
              },
              {
                href: '/crumb-2',
                title: 'There',
              },
              {
                href: '/crumb-3',
                title: 'There',
              },
              {
                href: '/current-page',
                title: 'Here',
              },
            ],
            false: [
              {
                href: '/homepage',
                title: 'Home',
              },
              {
                href: '/crumb-1',
                title: 'There',
              },
              {
                href: '/crumb-2',
                title: 'There',
              },
              {
                href: '/current-page',
                title: 'Here',
              },
            ],
          }),
          false: figma.boolean('crumb-3', {
            true: [
              {
                href: '/homepage',
                title: 'Home',
              },
              {
                href: '/crumb-1',
                title: 'There',
              },
              {
                href: '/crumb-3',
                title: 'There',
              },
              {
                href: '/current-page',
                title: 'Here',
              },
            ],
            false: [
              {
                href: '/homepage',
                title: 'Home',
              },
              {
                href: '/crumb-1',
                title: 'There',
              },
              {
                href: '/current-page',
                title: 'Here',
              },
            ],
          }),
        }),
        false: figma.boolean('crumb-2', {
          true: figma.boolean('crumb-3', {
            true: [
              {
                href: '/homepage',
                title: 'Home',
              },
              {
                href: '/crumb-2',
                title: 'There',
              },
              {
                href: '/crumb-3',
                title: 'There',
              },
              {
                href: '/current-page',
                title: 'Here',
              },
            ],
            false: [
              {
                href: '/homepage',
                title: 'Home',
              },
              {
                href: '/crumb-2',
                title: 'There',
              },
              {
                href: '/current-page',
                title: 'Here',
              },
            ],
          }),
          false: figma.boolean('crumb-3', {
            true: [
              {
                href: '/homepage',
                title: 'Home',
              },
              {
                href: '/crumb-3',
                title: 'There',
              },
              {
                href: '/current-page',
                title: 'Here',
              },
            ],
            false: [
              {
                href: '/homepage',
                title: 'Home',
              },
              {
                href: '/current-page',
                title: 'Here',
              },
            ],
          }),
        }),
      }),
    },
    example: (props) => <Breadcrumbs crumbs={props.crumbs} />,
  }
);
