import React from 'react';
import { Box, Coachmark, Text, TextButton, FlexBox } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Coachmark,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=19366-27764',
  {
    props: {
      beak: figma.enum('beak', {
        right: 'right',
        left: 'left',
      }),
      position: figma.enum('position', {
        below: 'below',
        above: 'above',
      }),
      renderPopover: <FlexBox flexDirection="column" gap={8} alignItems="flex-start">
        <Text as="h3" variant="title-xs" m={0}>
          New feature
        </Text>
        <Text variant="p-small" color="text">
          Information about the new feature can go here. Here’s an extra sentence if you really need it.
        </Text>
        <Box alignSelf="flex-end">
          <TextButton size="normal" onClick={() => {}}>
            Button text
          </TextButton>
        </Box>
      </FlexBox>,
      children: <ExampleComponent>Coachmark wraps around this component</ExampleComponent>,
    },
    example: ({ children, beak, position, ...props }) => (
      <Coachmark
        popoverProps={{
          position,
          beak,
        }}
        shouldShow
        {...props}
      >
        {children}
      </Coachmark>
    ),
  }
);
