import { Coachmark } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Coachmark,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=19366%3A27764',
  {
    props: {
      beak: figma.enum('beak', {
        right: 'right',
        left: 'left',
      }),
      position: figma.enum('position', {
        below: 'below',
        above: 'above',
      }),
      renderPopover: '<Box>{Content goes here}</Box>',
      children: figma.children('.Card Content Title'),
    },
    example: ({ children, beak, position, ...props }) => (
      <Coachmark
        popoverProps={{
          position,
          beak,
        }}
        shouldShow
        {...props}
      >
        {children}
      </Coachmark>
    ),
  }
);
