import React from 'react';
import { Disclosure } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Disclosure,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=43343%3A19299',
  {
    props: {
      variant: figma.enum('variant', {
        default: 'default',
        subtle: 'subtle',
        transparent: 'transparent',
      }),
      hasBorder: figma.boolean('hasBorder'),
      spacing: figma.enum('spacing', {
        normal: 'normal',
        condensed: 'condensed',
        compact: 'compact',
      }),
      headingInfo: figma.nestedProps('.disclosureButton', {
        overline: figma.boolean('overline', {
          true: figma.textContent('overline'),
          false: undefined,
        }),
        subheading: figma.boolean('subheading', {
          true: figma.textContent('subheading'),
          false: undefined,
        }),
        heading: figma.textContent('heading'),
      }),
      body: figma.children('.disclosureBody'),
      isExpanded: figma.boolean('isExpanded'),
      panelInfo: figma.nestedProps('.disclosureBody', {
        hasPanelBg: figma.boolean('hasPanelBg'),
        ctaText: figma.boolean('cta', {
          true: 'Button Text',
        }),
      }),
      buttonInfo: figma.nestedProps('.cta', {
        buttonPlacement: figma.enum('buttonPlacement', {
          left: 'left',
          right: 'right',
        }),
      }),
    },
    example: ({
      headingInfo,
      buttonInfo,
      body,
      variant,
      hasBorder,
      spacing,
      isExpanded,
      panelInfo,
    }) => (
      <Disclosure
        body={body}
        ctaText={panelInfo.ctaText}
        hasBorder={hasBorder}
        hasPanelBg={panelInfo.hasPanelBg}
        heading={headingInfo.heading}
        initiallyExpanded={isExpanded}
        overline={headingInfo.overline}
        spacing={spacing}
        subheading={headingInfo.subheading}
        variant={variant}
        buttonPlacement={buttonInfo.buttonPlacement}
      />
    ),
  }
);
