import { Flyout } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Flyout,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=6329%3A5647',
  {
    props: {
      openFrom: figma.enum('openFrom', {
        left: 'left',
        right: 'right',
      }),
      drawerInfo: figma.nestedProps('Drawer', {
        title: figma.textContent('Title'),
        children: figma.textContent('text'),
      }),
      closeLabel: 'Close',
      bg: 'background',
    },
    example: ({ drawerInfo, openFrom, closeLabel, bg }) => (
      <Flyout
        bg={bg}
        closeLabel={closeLabel}
        expanded
        openFrom={openFrom}
        title={drawerInfo.title}
        onClose={drawerInfo.onClose}
      >
        {drawerInfo.children}
      </Flyout>
    ),
  }
);
