import { Pagination } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Pagination,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=8629%3A9005',
  {
    props: {
      style: figma.enum('style', {
        text: 'text',
        stroke: 'stroke',
      }),
      type: figma.enum('type', {
        basic: 'basic',
        includeSkipToButtons: 'includeskiptobuttons',
      }),
    },
    example: (props) => <Pagination {...props} />,
  }
);
