import React from 'react';
import { Pagination } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Pagination,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=8629%3A9005',
  {
    props: {
      variant: figma.enum('style', {
        text: 'text',
        stroke: 'stroke',
      }),
      type: figma.enum('type', {
        basic: 'basic',
        includeSkipToButtons: 'includeSkipToButtons',
      }),
      chapterSize: figma.enum('chapterSize', {
        '2': 2,
        '3': 3,
        '4': 4,
        '5': 5,
        '6': 6,
        '7': 7,
        '8': 8,
      }),
    },
    // Note: totalPages and onChange are required props, but are not used in the example, these are placeholder values
    example: (props) => (
      <Pagination {...props} totalPages={10} onChange={() => { }} />
    ),
  }
);
