import React from 'react';
import { Popover } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Popover,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=106812-57101',
  {
    props: {
      beak: figma.boolean('beak'),
      position: figma.boolean('beak', {
        true: figma.enum('position', {
          above: 'above',
          below: 'below',
          'center-right': 'center',
          'center-left': 'center',
        }),
      }),
      align: figma.boolean('beak', {
        true: figma.enum('beakPosition', {
          left: 'left',
          right: 'right',
          center: figma.enum('position', {
            above: 'center',
            below: 'center',
            'center-left': 'left',
            'center-right': 'right',
          }),
        }),
      }),
      widthRestricted: figma.boolean('widthRestricted'),
      pattern: figma.children('Pattern Fills'),
      children: figma.textContent('text'),
      isOpen: true,
    },
    example: ({ children, ...props }) => (
      <Popover {...props}>{children}</Popover>
    ),
  }
);
