import React from 'react';
import { Tab } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Tab,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=8516%3A7309',
  {
    props: {
      badge: figma.boolean('badge', {
        true: '<Badge>Badge</Badge>',
        false: undefined,
      }),
      children: figma.string('label'),
      disabled: figma.enum('state', {
        Default: undefined,
        Selected: undefined,
        Disabled: true,
      }),
      selected: figma.enum('state', {
        Default: undefined,
        Disabled: undefined,
        Selected: true,
      }),
      hover: figma.boolean('hover'),
    },
    example: ({ children, badge, ...props }) => (
      <Tab {...props}>
        {children}
        {badge}
      </Tab>
    ),
  }
);
