import * as Icons from '@codecademy/gamut-icons';

/**
 * @deprecated Directly import icons from @codecademy/gamut-icons instead.
 */
const iconMap = {
  // alexa: Icons.AlexaIcon,
  // angular: Icons.AngularIcon,
  // bayes: Icons.BayesIcon,
  // jQuery: Icons.jQueryIcon,
  // java: Icons.JavaIcon,
  // javascript: Icons.JavascriptIcon,
  // css: Icons.CSSIcon,
  // daw: Icons.DAWIcon,
  // fullstack: Icons.FullstackIcon,
  // html: Icons.HTMLIcon,
  // git: Icons.GitIcon,
  // matplotLib: Icons.MatplotLibIcon,
  // maw: Icons.MAWIcon,
  // php: Icons.PHPIcon,
  // ruby: Icons.RubyIcon,
  // sass: Icons.SassIcon,
  // sciPy: Icons.SciPyIcon,
  // tdd: Icons.TDDIcon,
  // watson: Icons.WatsonIcon,
  // sql: Icons.SQLIcon,
  // numPy: Icons.NumPyIcon,
  // pandas: Icons.PandasIcon,
  // python: Icons.PythonIcon,
  // rails: Icons.RailsIcon,
  // react: Icons.ReactIcon,
  accessibility: Icons.AccessibilityIcon,
  add: Icons.AddIcon,
  advisor: Icons.PersonIcon,
  advisorChat: Icons.PersonChatIcon,
  alert: Icons.AlertIcon,
  article: Icons.ArticleIcon,
  bell: Icons.BellIcon,
  bulbIcon: Icons.BulbIcon,
  certificate: Icons.CertificateIcon,
  checkmark: Icons.CheckIcon,
  checkFilledIcon: Icons.CheckFilledIcon,
  chevronDown: Icons.ArrowChevronDownIcon,
  chevronLeft: Icons.ArrowChevronLeftIcon,
  chevronRight: Icons.ArrowChevronRightIcon,
  chevronUp: Icons.ArrowChevronUpIcon,
  clock: Icons.ClockIcon,
  close: Icons.CloseIcon,
  colors: Icons.IntersectionIcon,
  community: Icons.ChatIcon,
  copy: Icons.CopyIcon,
  downArrow: Icons.ArrowDownIcon,
  edit: Icons.EditIcon,
  floatIcon: Icons.LifePreserverIcon,
  forums: Icons.PeopleIcon,
  forumsChat: Icons.ForumsChatIcon,
  glasses: Icons.GlassesIcon,
  informational: Icons.InfoIcon,
  learn: Icons.LearnIcon,
  leftArrow: Icons.ArrowLeftIcon,
  lesson: Icons.LessonIcon,
  maintenance: Icons.MaintenanceIcon,
  menu: Icons.MenuIcon,
  newPageIcon: Icons.OpenIcon,
  path: Icons.PathIcon,
  phone: Icons.PhoneIcon,
  play: Icons.PlayIcon,
  practice: Icons.PracticeIcon,
  project: Icons.ProjectIcon,
  quiz: Icons.QuizIcon,
  reset: Icons.ResetIcon,
  responsive: Icons.ResponsiveIcon,
  rightArrow: Icons.ArrowRightIcon,
  search: Icons.SearchIcon,
  syllabus: Icons.LessonIcon,
  terminal: Icons.TerminalIcon,
  trophy: Icons.TrophyIcon,
  type: Icons.TypeIcon,
  upArrow: Icons.ArrowUpIcon,
  video: Icons.PlayIcon,
};

/**
 * @deprecated Directly import icons from @codecademy/gamut instead.
 */
export default iconMap;
