import figma from '@figma/code-connect';

import { Anchor, AnchorProps } from '../gamut/src/Anchor/index';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Anchor,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=19220%3A21856',
  {
    props: {
      children: figma.string('✏️ label'),
      icon: figma.instance<React.FunctionComponent>('↳ icon'),
      variant: figma.enum('variant', {
        Inline: 'inline',
        Interface: 'interface',
        Standard: 'standard',
        'Standard-secondary': 'standard-secondary',
      }),
    },
    example: (props: AnchorProps) => (
      <Anchor icon={props.icon} variant={props.variant}>
        {props.children}
      </Anchor>
    ),
  }
);
