import figma from '@figma/code-connect';

import { AnimatedFadeButton } from '../gamut/src/Pagination/AnimatedPaginationButtons';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  AnimatedFadeButton,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=8068%3A7683',
  {
    props: {
      type: figma.enum('type', {
        Page: 'page',
        Prev: 'prev',
        Next: 'next',
        'Next Ellipsis': 'next-ellipsis',
        'Prev Ellipsis': 'prev-ellipsis',
        Pagination: 'pagination',
      }),
      state: figma.enum('state', {
        Active: 'active',
        'Active + Hover': 'active---hover',
        Default: 'default',
        Hover: 'hover',
        Item: 'item',
      }),
      style: figma.enum('style', {
        text: 'text',
        stroke: 'stroke',
      }),
    },
    example: (props) => <AnimatedFadeButton {...props} />,
  }
);
