import figma from '@figma/code-connect';

import { Breadcrumb } from '../gamut/src/Breadcrumbs/index';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Breadcrumb,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=54229%3A24977',
  {
    props: {
      currenttitle: figma.string('current-title'),
      crumb2: figma.boolean('crumb-2'),
      crumb1: figma.boolean('crumb-1'),
      crumb3: figma.boolean('crumb-3'),
      anchorVariant: figma.enum('anchor variant', {
        interface: 'interface',
        standard: 'standard',
      }),
    },
    example: (props) => <Breadcrumb {...props} />,
  }
);
