import React from "react"
import { Column } from "../gamut/src/Layout/Column"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Column,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=9697%3A20746",
  {
    props: {
      columnWidth: figma.enum("Column Width", {
        xl: "xl",
        lg: "lg",
        md: "md",
        sm: "sm",
      }),
      type: figma.enum("Type", {
        Text: "text",
        Number: "number",
        "Text+Stat": "text-stat",
        Array: "array",
      }),
      size: figma.enum("Size", {
        Normal: "normal",
        Condensed: "condensed",
      }),
      firstColumn: figma.boolean("First Column"),
    },
    example: (props) => <Column />,
  },
)
