import figma from '@figma/code-connect';

import { DisclosureButton } from '../gamut/src/Disclosure/DisclosureButton/index';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  DisclosureButton,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=43343%3A3360',
  {
    props: {
      header: figma.string('header'),
      overline: figma.string('overline'),
      subheader: figma.string('subheader'),
    },
    example: (props) => <DisclosureButton {...props} />,
  }
);
