import figma from "@figma/code-connect"
import React from "react"

import { DisclosureBody } from "../gamut/src/Disclosure/DisclosureBody/index"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DisclosureBody,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=43655%3A4818",
  {
    props: {
      text: figma.string("text"),
      cta: figma.boolean("cta"),
      buttontype: figma.instance("button-type"),
      bodybg: figma.boolean("body-bg"),
    },
    example: (props) => <DisclosureBody {...props} />,
  },
)
