import figma from '@figma/code-connect';

import { ExpandControl } from '../gamut/src/DataList/Controls/ExpandControl';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ExpandControl,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=43553%3A22432',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      expanded: figma.boolean('isExpanded'),
      // No matching props could be found for these Figma properties:
      // "size": figma.enum('size', {
      //   "normal": "normal",
      //   "small": "small"
      // })
    },
    example: (props) => <ExpandControl expanded={props.expanded} />,
  }
);
