import React from "react"
import { FillButton } from "../gamut/src/Button/FillButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FillButton,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1106%3A7",
  {
    props: {
      leadingIcon: figma.boolean("👁 leading icon"),
      trailingIcon: figma.boolean("👁 trailing icon"),
      leadingIcon: figma.instance("↳ leading icon"),
      trailingIcon: figma.instance("↳ trailing icon"),
      label: figma.string("✏️ label"),
      variant: figma.enum("variant", {
        primary: "primary",
        secondary: "secondary",
        danger: "danger",
      }),
      size: figma.enum("size", {
        normal: "normal",
        small: "small",
        large: "large",
      }),
      state: figma.enum("state", {
        default: "default",
        hover: "hover",
        active: "active",
        focus: "focus",
        disabled: "disabled",
      }),
    },
    example: (props) => <FillButton />,
  },
)
