import React from "react"
import { FloatingTip } from "../gamut/src/Tip/shared/FloatingTip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  FloatingTip,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=59683%3A4547",
  {
    props: {},
    example: (props) => (
      <FloatingTip info={/* TODO */} alignment={/* TODO */} type={/* TODO */} />
    ),
  },
)
