import React from "react"
import { Flyout } from "../gamut/src/Flyout/index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Flyout,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=6329%3A5647",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      openFrom: figma.enum("openFrom", {
        left: "left",
        right: "right",
      }),
      // No matching props could be found for these Figma properties:
      // "size": figma.enum('size', {
      //   "desktop": "desktop",
      //   "mobile": "mobile"
      // })
    },
    example: (props) => (
      <Flyout
        closeLabel={/* TODO */}
        onClose={/* TODO */}
        openFrom={props.openFrom}
        title={/* TODO */}
      />
    ),
  },
)
