import React from "react"
import { FormGroupLabel } from "../gamut/src/Form/elements/FormGroupLabel"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FormGroupLabel,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=47031%3A18018",
  {
    props: {
      label: figma.string("✏️ label"),
      infoTip: figma.boolean("infoTip"),
      required: figma.boolean("required"),
      size: figma.enum("size", {
        small: "small",
        large: "large",
      }),
    },
    example: (props) => <FormGroupLabel />,
  },
)
