import figma from '@figma/code-connect';

import { GridForm } from '../gamut/src/GridForm/GridForm';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  GridForm,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1689%3A4007',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "requiredFields": figma.boolean('requiredFields?'),
      // "header": figma.string('header'),
      // "template": figma.enum('Template', {
      //   "Starter": "starter",
      //   "Sections": "sections",
      //   "Inline Submit": "inline-submit",
      //   "Instructions": "instructions"
      // })
    },
    example: (props) => (
      <GridForm submit={/* TODO */} onSubmit={/* TODO */} {...props} />
    ),
  }
);
