import React from "react"
import { GridFormButtons } from "../gamut/src/GridForm/GridFormButtons/index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  GridFormButtons,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1689%3A3911",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      position: figma.enum("Position", {
        Center: "center",
        Left: "left",
        Right: "right",
      }),
      type: figma.enum("Button Type", {
        Fill: "fill",
        CTA: "cta",
      }),
      // No matching props could be found for these Figma properties:
      // "cancel": figma.boolean('Cancel')
    },
    example: (props) => (
      <GridFormButtons
        contents={/* TODO */}
        position={props.position}
        size={/* TODO */}
        type={props.type}
      />
    ),
  },
)
