import figma from '@figma/code-connect';

import { GridFormSection } from '../gamut/src/GridForm/GridFormSections/GridFormSection';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  GridFormSection,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=57627%3A47911',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "item02": figma.boolean('.item-02'),
      // "item03": figma.boolean('.item-03'),
      // "item04": figma.boolean('.item-04'),
      // "item05": figma.boolean('.item-05'),
      // "item06": figma.boolean('.item-06'),
      // "item07": figma.boolean('.item-07'),
      // "item08": figma.boolean('.item-08'),
      // "item09": figma.boolean('.item-09'),
      // "item10": figma.boolean('.item-10'),
      // "item11": figma.boolean('.item-11'),
      // "item12": figma.boolean('.item-12'),
      // "item13": figma.boolean('.item-13'),
      // "item14": figma.boolean('.item-14'),
      // "item15": figma.boolean('.item-15'),
      // "item16": figma.boolean('.item-16'),
      // "item17": figma.boolean('.item-17'),
      // "item18": figma.boolean('.item-18'),
      // "item19": figma.boolean('.item-19'),
      // "item20": figma.boolean('.item-20'),
      // "expanded": figma.boolean('expanded')
    },
    example: (props) => <GridFormSection fields={/* TODO */} />,
  }
);
