import figma from '@figma/code-connect';

import { ImageContainer } from '../gamut/src/Modals/ImageContainer';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ImageContainer,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=29492%3A37582',
  {
    props: {},
    example: (props) => <ImageContainer />,
  }
);
