import React from "react"
import { InfoTip } from "../gamut/src/Tip/InfoTip/index"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  InfoTip,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=36743%3A20136",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      emphasis: figma.enum("emphasis", {
        low: "low",
        high: "high",
      }),
      // No matching props could be found for these Figma properties:
      // "state": figma.enum('state', {
      //   "default": "default",
      //   "hover": "hover",
      //   "active": "active",
      //   "focus": "focus",
      //   "disabled": "disabled"
      // })
    },
    example: (props) => <InfoTip info={/* TODO */} emphasis={props.emphasis} />,
  },
)
