import React from "react"
import { Input } from "../gamut/src/Form/inputs/Input"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Input,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1189%3A590",
  {
    props: {
      icon: figma.boolean("icon"),
      disabledText: figma.string("disabled text"),
      fileName: figma.string("file name"),
      state: figma.enum("state", {
        enabled: "enabled",
        hover: "hover",
        focus: "focus",
        valid: "valid",
        "valid+hover": "valid-hover",
        "valid+focus": "valid-focus",
        error: "error",
        "error+hover": "error-hover",
        "error+focus": "error-focus",
        disabled: "disabled",
      }),
      type: figma.enum("type", {
        text: "text",
        number: "number",
        file: "file",
      }),
      size: figma.enum("size", {
        base: "base",
        small: "small",
      }),
    },
    example: (props) => <Input />,
  },
)
