import figma from '@figma/code-connect';

import { MarkdownVideo } from '../gamut/src/Markdown/libs/overrides/Video/index';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  MarkdownVideo,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=73447%3A73063',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "breakpoint": figma.enum('breakpoint', {
      //   "676px+": "676px-",
      //   "<676px": "-676px"
      // })
    },
    example: (props) => <MarkdownVideo {...props} />,
  }
);
