import figma from '@figma/code-connect';

import { Popover } from '../gamut/src/Popover/Popover';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Popover,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=19005%3A20881',
  {
    props: {
      active: figma.boolean('Active'),
      pattern: figma.boolean('Pattern'),
      focusable: figma.boolean('Focusable'),
      bordered: figma.boolean('Bordered'),
      beak: figma.boolean('Beak'),
    },
    example: (props) => <Popover {...props} />,
  }
);
