import figma from '@figma/code-connect';

import { ProgressBar, ProgressBar } from '../gamut/src/ProgressBar/index';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ProgressBar,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=18640%3A20613',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "size": figma.enum('size', {
      //   "Large": "large",
      //   "Medium": "medium",
      //   "Small": "small",
      //   "XL": "xl"
      // }),
      // "variant": figma.enum('variant', {
      //   "default": "default",
      //   "yellow": "yellow",
      //   "blue": "blue"
      // }),
      // "percent": figma.enum('percent', {
      //   "0%": "0-",
      //   "25%": "25-",
      //   "50%": "50-",
      //   "75%": "75-",
      //   "100%": "100-"
      // }),
      // "pattern": figma.boolean('pattern'),
      // "flat": figma.enum('flat', {
      //   "n/a": "n-a",
      //   "flat-top": "flat-top",
      //   "flat-bottom": "flat-bottom"
      // })
    },
    example: (props) => (
      <ProgressBar percent={/* TODO */} variant={/* TODO */} />
    ),
  }
);

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ProgressBar,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=55037%3A17087',
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "barwidth": figma.enum('bar-width', {
      //   "10%": "10-",
      //   "20%": "20-",
      //   "30%": "30-",
      //   "40%": "40-",
      //   "50%": "50-",
      //   "60%": "60-",
      //   "70%": "70-",
      //   "80%": "80-",
      //   "90%": "90-",
      //   "100%": "100-"
      // })
    },
    example: (props) => (
      <ProgressBar percent={/* TODO */} variant={/* TODO */} />
    ),
  }
);
