import React from "react"
import { Radio } from "../gamut/src/Form/inputs/Radio"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Radio,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1191%3A1622",
  {
    props: {
      label: figma.string("✏️ label"),
      infoTip: figma.boolean("infoTip"),
      state: figma.enum("state", {
        enabled: "enabled",
        hover: "hover",
        active: "active",
        focus: "focus",
        error: "error",
        disabled: "disabled",
      }),
      selected: figma.boolean("selected"),
    },
    example: (props) => <Radio />,
  },
)
