import figma from '@figma/code-connect';

import { Select } from '../gamut/src/Form/inputs/Select';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Select,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=70050%3A14802',
  {
    props: {
      leadingicon: figma.boolean('leading-icon'),
      option5: figma.boolean('option-5'),
      option4: figma.boolean('option-4'),
      option3: figma.boolean('option-3'),
      selection: figma.string('✏️ selection'),
      state: figma.enum('state', {
        Enabled: 'enabled',
        Hover: 'hover',
        Focus: 'focus',
        Active: 'active',
        Filled: 'filled',
        'Filled + Hover': 'filled---hover',
        'Filled + Focus': 'filled---focus',
        'Filled + Active': 'filled---active',
        Error: 'error',
        Disabled: 'disabled',
      }),
      sizeVariant: figma.enum('sizeVariant', {
        base: 'base',
        small: 'small',
      }),
    },
    example: (props) => <Select />,
  }
);
