import React from "react"
import { Tab } from "../gamut/src/Tabs/Tab"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Tab,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=8516%3A7309",
  {
    props: {
      badge: figma.boolean("badge"),
      label: figma.string("label"),
      state: figma.enum("state", {
        Default: "default",
        Selected: "selected",
        Disabled: "disabled",
      }),
      hover: figma.boolean("hover"),
    },
    example: (props) => <Tab />,
  },
)
