import React from "react"
import { Tabs } from "../gamut/src/Tabs/Tabs"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Tabs,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=8516%3A7564",
  {
    props: {
      tab3: figma.boolean("tab-3"),
      tab4: figma.boolean("tab-4"),
      tab5: figma.boolean("tab-5"),
      tab6: figma.boolean("tab-6"),
      scrollback: figma.boolean("scroll-back"),
      scrollnext: figma.boolean("scroll-next"),
      style: figma.enum("style", {
        default: "default",
        "full-width": "full-width",
      }),
    },
    example: (props) => <Tabs />,
  },
)
