import figma from '@figma/code-connect';

import { ToolTip } from '../gamut/src/Tip/ToolTip/index';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ToolTip,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=41215%3A28041',
  {
    props: {
      // These props were automatically mapped based on your linked code:
      alignment: figma.enum('alignment', {
        'bottom-center': 'bottom-center',
        'left-center': 'left-center',
        'right-center': 'right-center',
        'top-center': 'top-center',
      }),
      // No matching props could be found for these Figma properties:
      // "tooltip": figma.string('✏️ tooltip'),
      // "targetarea": figma.boolean('👁️ target-area'),
      // "targetHeight": figma.enum('target height', {
      //   "32px": "32px",
      //   "40px": "40px",
      //   "56px": "56px"
      // })
    },
    example: (props) => (
      <ToolTip alignment={props.alignment} info={/* TODO */} />
    ),
  }
);
