import figma from "@figma/code-connect"

import { IconButton } from "./IconButton"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  IconButton,
  "https://www.figma.com/design/2cQBxc5JTO0M38mcYARs7O/codeConnect?node-id=1106-90&m=dev",
  {
    props: {
      icon: figma.instance("icon"),
      iconmini: figma.instance("icon-mini"),
      variant: figma.enum("variant", {
        primary: "primary",
        secondary: "secondary",
        danger: "danger",
      }),
      size: figma.enum("size", {
        normal: "normal",
        small: "small",
        large: "large",
      }),
      state: figma.enum("state", {
        default: "default",
        hover: "hover",
        active: "active",
        focus: "focus",
        disabled: "disabled",
        "disabled + hover": "disabled---hover",
      }),
    },
    example: (props) => (<IconButton icon={props.icon || props.iconmini} size={props.size} state={props.state}/>),
  },
)
