import React from "react"
import { IconButton } from "./IconButton"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  IconButton,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1106%3A90",
  {
    props: {
      iconmini: figma.instance("icon-mini"),
      icon: figma.instance("icon"),
      variant: figma.enum("variant", {
        primary: "primary",
        secondary: "secondary",
        danger: "danger",
      }),
      size: figma.enum("size", {
        normal: "normal",
        small: "small",
        large: "large",
      }),
      state: figma.enum("state", {
        default: "default",
        hover: "hover",
        active: "active",
        focus: "focus",
        disabled: "disabled",
        "disabled + hover": "disabled---hover",
      }),
    },
    example: (props) => <IconButton />,
  },
)
