import figma from '@figma/code-connect';

import {
  ListRow,
  ListCol,
  Box,
  Rotation,
  FillButton,
  TextButton,
} from '@codecademy/gamut';
import { ArrowChevronDownIcon } from '@codecademy/gamut-icons';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ListRow,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=7080-4776',
  {
    props: {
      isExpanded: figma.boolean('↳ Expanded'),
      renderExpanded: figma.boolean('Expandable', {
        true: () => <Box>Expandable Content Here</Box>,
        false: undefined,
      }),
      controlSection: figma.boolean('Expandable', {
        true: figma.boolean('↳ Expanded', {
          true: (
            <ListCol type="control">
              <Rotation rotated={true}>
                <ArrowChevronDownIcon color="text-disabled" />
              </Rotation>
            </ListCol>
          ),
          false: (
            <ListCol type="control">
              <Rotation rotated={false}>
                <ArrowChevronDownIcon color="text-disabled" />
              </Rotation>
            </ListCol>
          ),
        }),
        false: (
          <ListCol type="control">
            <TextButton>Controls</TextButton>
            <FillButton>Controls</FillButton>
          </ListCol>
        ),
      }),
    },
    example: ({ isExpanded, renderExpanded, controlSection }) => (
      <ListRow expanded={isExpanded} renderExpanded={renderExpanded}>
        <ListCol type="header">Title</ListCol>
        <ListCol type="content">Item 1</ListCol>
        <ListCol type="content">Item 2</ListCol>
        <ListCol type="content">Item 3</ListCol>
        {controlSection}
      </ListRow>
    ),
  }
);
