import { List } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  List,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=7080-4860',
  {
    props: {
      variant: figma.enum('variant', {
        Base: 'default',
        Card: 'card',
        Table: 'table',
        Block: 'block',
      }),
      spacing: figma.enum('size', {
        Normal: 'normal',
        Condensed: 'condensed',
      }),
      children: figma.children('*'),
    },
    example: ({ children, ...props }) => <List {...props}>{children}</List>,
  }
);
