import React from "react"
import { Dialog } from "./Dialog"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Dialog,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=19781%3A31027",
  {
    props: {
      image: figma.boolean("Image"),
      secondaryAction: figma.boolean("secondary action"),
      size: figma.enum("size", {
        small: "small",
        medium: "medium",
        large: "large",
        fluid: "fluid",
      }),
      variant: figma.enum("variant", {
        primary: "primary",
        danger: "danger",
      }),
    },
    example: (props) => <Dialog />,
  },
)
