import React from "react"
import { Modal } from "./Modal"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Modal,
  "https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=19560%3A29540",
  {
    props: {
      property1: figma.enum("Property 1", {
        Default: "default",
      }),
    },
    example: (props) => <Modal />,
  },
)
