import { Checkbox } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1199%3A270',
  {
    props: {
      label: figma.string('✏️ label'),
      checked: figma.enum('checked', {
        true: 'true',
        false: 'false',
        Indeterminate: 'false',
      }),
      indeterminate: figma.enum('checked', {
        true: 'false',
        false: 'false',
        Indeterminate: 'true',
      }),
      ariaLabel: figma.string('✏️ label'),
    },
    example: ({ ariaLabel, ...props }) => (
      <Checkbox {...props} aria-label={ariaLabel} />
    ),
  }
);
