import React from 'react';
import { Radio } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Radio,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1191%3A1622',
  {
    props: {
      label: figma.string('✏️ label'),
      checked: figma.boolean('selected'),
      disabled: figma.enum('state', {
        enabled: false,
        hover: false,
        active: false,
        focus: false,
        error: false,
        disabled: true,
      }),
      error: figma.enum('state', {
        enabled: false,
        hover: false,
        active: false,
        focus: false,
        error: true,
        disabled: false,
      }),
      hasInfotip: figma.boolean('infoTip', {
        true: true,
        false: false,
      }),
      hasEmphasis: figma.nestedProps('infotip', {
        emphasis: figma.enum('emphasis', { low: 'low', high: 'high' }),
      }),
      toolTipInfo: figma.nestedProps('.infotip-alignment', {
        alignment: figma.enum('alignment', {
          'top-left': 'top-left',
          'top-right': 'top-right',
          'bottom-left': 'bottom-left',
          'bottom-right': 'bottom-right',
        }),
        info: figma.string('✏️ info tip'),
      }),
    },
    example: (props) => (
      <Radio
        {...props}
        infotip={{
          emphasis: props.hasEmphasis?.emphasis,
          info: props.toolTipInfo?.info,
          alignment: props.toolTipInfo?.alignment,
        }}
      />
    ),
  }
);
