import React from 'react';
import { SelectDropdown } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SelectDropdown,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1487%3A1657',
  {
    props: {
      disabled: figma.enum('state', {
        disabled: true,
        'filled + disabled': true,
      }),
      error: figma.enum('state', {
        error: true,
        'filled + error': true,
      }),
      size: figma.enum('size', {
        small: 'small',
        medium: 'medium',
      }),
      options: figma.children('option-*'),
      isSearchable: figma.boolean('isSearchable'),
      placeholder: figma.boolean('placeholder', {
        true: figma.textContent('placeholder'),
        false: undefined,
      }),
      multiple: figma.boolean('multiple'),
    },
    example: (props) => <SelectDropdown {...props} />,
  }
);
