import { SelectDropdown } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SelectDropdown,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1487%3A1657',
  {
    props: {
      disabled: figma.enum('state', {
        Disabled: true,
      }),
      error: figma.enum('state', {
        Error: true,
      }),
      size: figma.enum('size', {
        small: 'small',
        medium: 'medium',
      }),
      options: figma.children('option-*'),
      placeholder: figma.enum('state', {
        Enabled: figma.textContent('placeholder'),
        Hover: figma.textContent('placeholder'),
        Focus: figma.textContent('placeholder'),
        Active: figma.textContent('placeholder'),
      }),
      defaultValue: figma.enum('state', {
        Filled: figma.textContent('selection'),
        'Filled + Hover': figma.textContent('selection'),
        'Filled + Focus': figma.textContent('selection'),
        'Filled + Active': figma.textContent('selection'),
        Error: figma.textContent('selection'),
        Disabled: figma.textContent('selection'),
      }),
    },
    example: (props) => <SelectDropdown {...props} />,
  }
);
