import React from 'react';
import { Select } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Select,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=70050%3A14802',
  {
    props: {
      sizeVariant: figma.enum('sizeVariant', {
        base: 'base',
        small: 'small',
      }),
      disabled: figma.enum('state', {
        Enabled: false,
        Hover: false,
        Focus: false,
        Active: false,
        Filled: false,
        'Filled + Hover': false,
        'Filled + Focus': false,
        'Filled + Active': false,
        Error: false,
        Disabled: true,
      }),
      error: figma.enum('state', {
        Enabled: false,
        Hover: false,
        Focus: false,
        Active: false,
        Filled: false,
        'Filled + Hover': false,
        'Filled + Focus': false,
        'Filled + Active': false,
        Error: true,
        Disabled: false,
      }),
      options: figma.children('option-*'),
      defaultValue: figma.string('selection'),
    },
    example: (props) => <Select {...props} />,
  }
);
