import { SelectDropdown } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SelectDropdown,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1487%3A1657',
  {
    props: {
      disabled: figma.enum('state', {
        Disabled: true,
      }),
      error: figma.enum('state', {
        Error: true,
      }),
      size: figma.enum('size', {
        small: 'small',
        medium: 'medium',
      }),
      options: figma.children('option-*'),
      defaultValue: figma.string('✏️ selection'),
    },
    // @ts-expect-error - figma.children() returns JSX elements but SelectDropdown expects Record<string, string>
    example: (props) => <SelectDropdown {...props} />,
  }
);
