import React from 'react';
import { TextArea } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TextArea,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=1484%3A141',
  {
    props: {
      disabled: figma.enum('state', {
        Enabled: false,
        Inactive: false,
        Hover: false,
        Focus: false,
        Error: false,
        Disabled: true,
      }),
      error: figma.enum('state', {
        Enabled: false,
        Inactive: false,
        Hover: false,
        Focus: false,
        Error: true,
        Disabled: false,
      }),
      defaultValue: figma.enum('state', {
        filled: figma.textContent('input'),
        'filled + hover': figma.textContent('input'),
        'filled + focus': figma.textContent('input'),
        error: figma.textContent('input'),
        'error + focus': figma.textContent('input'),
      }),
      placeholder: figma.enum('state', {
        enabled: figma.textContent('placeholder'),
        hover: figma.textContent('placeholder'),
        focus: figma.textContent('placeholder'),
        disabled: figma.textContent('placeholder'),
      }),
      rows: figma.enum('rows', {
        '2': 2,
        '3': 3,
        '4': 4,
        '5': 5,
        '6': 6,
      }),
    },
    example: (props) => <TextArea {...props} />,
  }
);
