import React from 'react';
import { InfoTip } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  InfoTip,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=36743%3A20136',
  {
    props: {
      emphasis: figma.enum('emphasis', {
        low: 'low',
        high: 'high',
      }),
      toolTipInfo: figma.nestedProps('.infotip-alignment', {
        alignment: figma.enum('alignment', {
          'top-left': 'top-left',
          'top-right': 'top-right',
          'bottom-left': 'bottom-left',
          'bottom-right': 'bottom-right',
        }),
        info: figma.textContent('✏️ tip'),
      }),
    },
    example: (props) => (
      <InfoTip
        {...props}
        alignment={props.toolTipInfo?.alignment}
        info={props.toolTipInfo?.info}
      />
    ),
  }
);
