import { PreviewTip } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  PreviewTip,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=49333-38735&m=dev',
  {
    props: {
      previewTipProps: figma.nestedProps('.previewtip-alignment-anchor', {
        alignment: figma.enum('alignment', {
          'bottom-left': 'bottom-left',
          'bottom-right': 'bottom-right',
          'top-left': 'top-left',
          'top-right': 'top-right',
        }),
        overline: figma.boolean('overline', {
          true: figma.string('✏️ overline'),
          false: undefined,
        }),
        linkDescription: figma.textContent('✏️ snippet'),
        children: figma.textContent('✏️ label'),
      }),
    },
    example: ({ previewTipProps }) => (
      <PreviewTip
        alignment={previewTipProps.alignment}
        linkDescription={previewTipProps.linkDescription}
        overline={previewTipProps.overline}
      >
        {previewTipProps.children}
      </PreviewTip>
    ),
  }
);
