import React from 'react';
import { ToolTip } from '@codecademy/gamut';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ToolTip,
  'https://www.figma.com/design/ReGfRNillGABAj5SlITalN/%F0%9F%93%90-Gamut?node-id=41215%3A28041',
  {
    props: {
      alignment: figma.enum('alignment', {
        'bottom-center': 'bottom-center',
        'left-center': 'left-center',
        'right-center': 'right-center',
        'top-center': 'top-center',
      }),
      info: figma.string('✏️ tooltip'),
      children: '{children}',
    },
    example: ({ children, ...props }) => (
      <ToolTip {...props}>{children}</ToolTip>
    ),
  }
);
