export enum LanguageIds {
  codecademyCss = 'codecademy-css',
  codecademyDefault = 'plaintext',
  codecademyGo = 'codecademy-go',
  codecademyHtml = 'codecademy-html',
  codecademyJava = 'codecademy-java',
  codecademyJs = 'codecademy-js',
  codecademyPhp = 'codecademy-php',
  codecademyPython = 'codecademy-python',
  codecademyR = 'codecademy-r',
  codecademyRuby = 'codecademy-ruby',
  codecademyScss = 'codecademy-scss',
  codecademySql = 'codecademy-sql',
  codecademySwift = 'codecademy-swift',
  codecademyCSharp = 'codecademy-cs',
  codecademyCpp = 'codecademy-cpp',
  codecademyKotlin = 'codecademy-kotlin',
  codecademyRazor = 'codecademy-razor',
}
