export enum LanguageId {
  CodecademyCss = 'codecademy-css',
  CodecademyDefault = 'plaintext',
  // CodecademyGo = 'codecademy-go',
  // CodecademyHtml = 'codecademy-html',
  // CodecademyJava = 'codecademy-java',
  CodecademyJs = 'codecademy-js',
  // CodecademyPhp = 'codecademy-php',
  // CodecademyPython = 'codecademy-python',
  // CodecademyR = 'codecademy-r',
  // CodecademyRuby = 'codecademy-ruby',
  // CodecademyScss = 'codecademy-scss',
  // CodecademySql = 'codecademy-sql',
  // CodecademySwift = 'codecademy-swift',
  // CodecademyCSharp = 'codecademy-cs',
  // CodecademyCpp = 'codecademy-cpp',
  // CodecademyKotlin = 'codecademy-kotlin',
  // CodecademyRazor = 'codecademy-razor',
}
