# This workflow announces the new release on the TBA Some Gamut Release Slack channel
name: Announce the release on Slack

on:
  release:
    types: [published]

jobs:
  announce-release-on-slack:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.release.body, 'Version bump only for package') }}
    steps:
      - name: Slackify the release body
        id: release_body
        uses: LoveToKnow/slackify-markdown-action@v1.0.0
        with:
          text: ${{ github.event.release.body }}
      - name: Announce changelog on Slack
        uses: homeday-de/slack-release-bot-action@v0.0.1
        with:
          webhook_url: ${{ secrets.SLACK_RELEASE_BOT_WEBHOOK_URL }}
          title: ${{ github.event.release.name }}
          body: ${{ steps.release_body.outputs.text }}
          context: Gamut

  announce-kit-version-on-slack:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.release.body, '@codecademy/gamut-kit') }}
    steps:
      - name: Announce on gamut-kit version on Slack
        uses: homeday-de/slack-release-bot-action@v0.0.1
        with:
          webhook_url: ${{ secrets.SLACK_RELEASE_BOT_WEBHOOK_URL }}
          title: ${{ github.event.release.name }}
          body: 'Include this package in your application instead of the individual packages to simplify version management.'
          context: gamut-kit
