name: lint-pr-name
on:
  repository_dispatch:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  trigger_lint:
    runs-on: ubuntu-latest
    steps:
      - if: github.event != 'repository_dispatch'
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: trigger-pr-name-lint

  lint:
    runs-on: ubuntu-latest
    steps:
    - if: github.event_name == 'trigger-pr-name-lint'
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install
    - uses: JulienKode/pull-request-name-linter-action@v0.1.0
