name: Publish Alpha

on:
  pull_request:
    branches-ignore:
      - production

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write
  actions: write

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set git user
        run: |
          git config --global user.email "dev@codecademy.com"
          git config --global user.name "codecademydev"
          git config --global push.default current

      - name: Set npm token
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: ./.github/actions/yarn

      - run: npx nx run-many --target=publish-build --parallel=3

      - name: Publish alpha packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn lerna publish --exact --yes --include-merged-tags --no-push --no-git-reset --conventional-commits --conventional-prerelease --preid=alpha.${{github.sha}} --dist-tag=alpha.${{github.sha}}

      - name: List alpha packages versions
        id: published
        continue-on-error: true
        run: |
          ALPHA_PACKAGES="$(yarn lerna ll --parseable | grep alpha || true)"
            if [ -z "$ALPHA_PACKAGES" ]
            then
              echo "No alpha published packages found, will not add PR comment"
            else
              echo result="$ALPHA_PACKAGES" >> $GITHUB_OUTPUT

      - name: Comment with published alpha packages
        uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db # v2.9.2
        if: steps.published.outputs.result
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: Alpha Packages
          recreate: true
          message: |
            ```
            ${{ steps.published.outputs.result }}
            ```
