name: Publish Alpha

on:
  pull_request:
    branches-ignore:
      - main

env:
  NODE_VERSION: '22.13.1'
  NODE_OPTIONS: '--max_old_space_size=8196'
  NX_CLOUD: false
  IGNORE_COMMIT_MESSAGE: 'chore(release): publish'

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write
  actions: write

jobs:
  publish-alpha:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{  github.event.pull_request.head.ref }}

      - name: Setup and Build
        id: setup
        uses: ./.github/actions/yarn
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          node-version: ${{ env.NODE_VERSION }}

      - name: Skip if automated commit
        if: steps.setup.outputs.should-skip == 'true'
        run: |
          echo "Skipping publish-alpha due to automated commit"
          exit 0

      - name: Set git user
        run: |
          git config --global user.email "dev@codecademy.com"
          git config --global user.name "codecademydev"
          git config --global push.default current

      - name: Check if able to publish changes
        run: npm whoami # will throw and exit if npm is not ready to publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish alpha packages
        run: |
          SHORT_SHA=${GITHUB_SHA:0:6}
          yarn lerna publish --no-verify-access --exact --yes --include-merged-tags --no-push --no-git-reset --conventional-commits --conventional-prerelease --preid=alpha.${SHORT_SHA} --dist-tag=alpha.${SHORT_SHA}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: List alpha packages versions
        id: published
        continue-on-error: true
        run: |
          ALPHA_PACKAGES="$(yarn lerna ll --parseable | grep alpha || true)"
            if [ -z "$ALPHA_PACKAGES" ]
            then
              echo "No alpha published packages found, will not add PR comment"
            else
              echo result="$ALPHA_PACKAGES" >> $GITHUB_OUTPUT

      - name: Comment with published alpha packages
        uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db # v2.9.2
        if: steps.published.outputs.result
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: Alpha Packages
          recreate: true
          message: |
            ```
            ${{ steps.published.outputs.result }}
            ```
