name: Publish Alpha

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  NODE_VERSION: '22.13.1'
  NODE_OPTIONS: '--max_old_space_size=8196'
  NX_CLOUD: false
  IGNORE_COMMIT_MESSAGE: 'chore(release): publish'

permissions:
  id-token: write
  contents: read
  pull-requests: write
  issues: write
  actions: write

concurrency:
  group: npm-prerelease-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  publish-alpha:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'beta') }}
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/prerelease-publish
        with:
          node-auth-token: ${{ secrets.NODE_AUTH_TOKEN }}
          gh-token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          ignore-commit-message: ${{ env.IGNORE_COMMIT_MESSAGE }}
          manifest-path: alpha-publish-manifest.json
          comment-path: alpha-publish-comment.md
          comment-title: Published Alpha Packages
          sticky-header: Alpha Packages
          publish-run: |
            SHORT_SHA=${GITHUB_SHA:0:6}
            PREID="alpha.${SHORT_SHA}"
            npx nx run gamut-release:pre-release --preid="${PREID}" --manifest
