name: Check labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, reopened]

jobs:
  ship-it:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.user.login != 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies') == 'false'
    steps:
      - uses: sugarshin/required-labels-action@v0.3.1
        with:
          required_all: 'Ship It :shipit:'
