import { GamutIconProps } from "@codecademy/gamut-icons"
import figma from "@figma/code-connect"
import { ComponentType } from "react"

import { Badge } from "./index"

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Badge,
  "https://www.figma.com/design/2cQBxc5JTO0M38mcYARs7O/codeConnect?node-id=8200-8349&t=CNJ54QWrGYXM00Di-4",
  {
    props: {
      leadingicon: figma.boolean("leading-icon"),
      icon: figma.instance("↳ icon"),
      label: figma.string("✏️ label"),
      variant: figma.enum("variant", {
        primary: "primary",
        secondary: "secondary",
        tertiary: "tertiary",
        accent: "accent",
        "tertiaryFill": "tertiaryFill",
      }),
      size: figma.enum("size", {
        base: "base",
        sm: "sm",
      }),
    },
    example: (props) => {
      return (<Badge icon={props.icon} variant={props.variant} size={props.size}>{props.label}</Badge>)
    }
  },
)
